version: '2'
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  connect:
    image: "debezium/connect:0.9"
    ports:
      - "8083:8083"
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - ADVERTISED_HOST_NAME=192.168.1.5
      - BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - mysql

  mysql:
    image: mysql:5.6.43
    container_name: debezium-mysql
    volumes:
      - "./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./data:/var/lib/mysql"
      - "./test_db:/test_db"
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306"
